// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pawtient_project.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace pawtient_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pawtient_project.Appointment.Domain.Models.Aggregates.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("APT_id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("APT_amount");

                    b.Property<int?>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLI_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("APT_created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("APT_date");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasDefaultValue("")
                        .HasColumnName("APT_owner");

                    b.Property<string>("Patient")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasDefaultValue("")
                        .HasColumnName("APT_patient");

                    b.Property<int?>("PetId")
                        .HasColumnType("int")
                        .HasColumnName("PET_id");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("APT_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("REQUESTED")
                        .HasColumnName("APT_status");

                    b.Property<string>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("")
                        .HasColumnName("APT_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("FIRST_VISIT")
                        .HasColumnName("APT_type");

                    b.Property<int?>("VeterinarianId")
                        .HasColumnType("int")
                        .HasColumnName("VET_id");

                    b.HasKey("Id");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("pawtient_project.Clinic.Domain.Models.Aggregates.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PET_id");

                    b.Property<int>("Age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("PET_age");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("PET_birth_date");

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("PET_breed_name");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLI_id");

                    b.Property<string>("CoatColor")
                        .HasColumnType("longtext")
                        .HasColumnName("PET_coat_color");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("PET_is_active");

                    b.Property<string>("Microchip")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PET_microchip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PET_name");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("UNKNOWN")
                        .HasColumnName("PET_sex");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("PET_species_name");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PET_weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("Microchip")
                        .IsUnique();

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("pawtient_project.IAM.Domain.Models.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USU_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("USU_created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("USU_email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("USU_full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("USU_password_hash");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Paw Care")
                        .HasColumnName("USU_plan_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("USU_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("USU_status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("pawtient_project.Profiles.Domain.Models.Aggregates.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLI_id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_name");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_phone");

                    b.Property<string>("Ruc")
                        .HasColumnType("longtext")
                        .HasColumnName("CLI_ruc");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USU_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clinics", (string)null);
                });

            modelBuilder.Entity("pawtient_project.Report.Domain.Models.Aggregates.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("INV_id");

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("INV_amount");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("APT_id");

                    b.Property<string>("Client")
                        .HasColumnType("longtext")
                        .HasColumnName("INV_client");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLI_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("INV_date");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("INV_notes");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext")
                        .HasColumnName("INV_owner_name");

                    b.Property<string>("Patient")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("INV_patient");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("INV_pet_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("INV_status");

                    b.HasKey("Id");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("pawtient_project.Store.Domain.Models.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRD_id");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLI_id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PRD_is_active");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int")
                        .HasColumnName("PRD_minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PRD_name");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("PRD_stock");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SUP_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRD_unit_price");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("pawtient_project.Store.Domain.Models.Aggregates.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUP_id");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasColumnName("SUP_category");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int")
                        .HasColumnName("CLI_id");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext")
                        .HasColumnName("SUP_contact");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("SUP_contact_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("SUP_name");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("SUP_phone");

                    b.Property<string>("Ruc")
                        .HasColumnType("longtext")
                        .HasColumnName("SUP_ruc");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("pawtient_project.Store.Domain.Models.Aggregates.Product", b =>
                {
                    b.HasOne("pawtient_project.Store.Domain.Models.Aggregates.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
